language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: windows
    dist: trusty
    python: '3.4'
  - os: linux
    dist: trusty
    python: '3.3'
  - os: linux
    dist: trusty
    python: '3.4'
  - os: linux
    dist: trusty
    python: '3.5'
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.

# command to install dependencies
install:
  - pip3 install fakeRPiGPIO
  - pip3 install coveralls
# command to run tests
script: 
 coverage run --source=Coliform setup.py test
after_success:
 coveralls
